# 关于Python3.7的异常的探究


>   编码过程中是会有一场诞生的，这是一定的。
    但是在已成诞生的时候，什么时候可以解决异常，
    而探查一场的是时候有事如何进行的。
    
Python是如何对异常进行处理的？

## 错误

* 举起小手（Raises）他的小手，
* 来告诉你那里出现了错误（Error）。

## 异常

* Try 去读取用户的输入内容,按下ctrl-D,

* EOFError 错误： 不应该出现的符号出现了。

## 处理异常

> 我们可以使用 try...except 处理异常一般来说，和其他的语言语法类似，
把语句放到try ... except 的包围中。

### 他是如何工作的？

* 我们把山哦呦可能出现的可能引发异常的事情，全部导入到try语句中，
这是没有什么问题的。但是问题来了，我的异常那可能是多种多样的，
Python是如何保证我的每一个错误或者异常都有有相应的异常提示？

所以，我们需要准备多种错误处理器，然后将每个错 误处理 器都放在可疑的语句下，然后对语句进行运行。
当初横序开始运行的时候，解释器开始对语句进行解释运行，然后如果出现了错误语句，
解释器就作出一个反应，识别出该错误属于什么错误类型，
然后开始与你所给出的错误类型相匹配，然后进行你的容错处理，或者错误解释


## 抛弃异常

你可以使用或者通过raise语句来引发一次异常，具体的方法是提供错误名或者异常名或者要抛出的异常对象。



### 工作原理



